apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k5txcqfrs-go 
  janus-idp.io/tekton: k5txcqfrs-go
  backstage.io/kubernetes-id: k5txcqfrs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k5txcqfrs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml